"""Setup main database

Revision ID: bf323ca06a5f
Revises: 
Create Date: 2024-05-03 09:08:33.110147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf323ca06a5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mod_lecture_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('exercise_id'),
    sa.UniqueConstraint('lecture_id'),
    sa.UniqueConstraint('mod_lecture_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('flows',
    sa.Column('flow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('A', 'B', 'C', 'D', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('flow_id')
    )
    op.create_table('flow_exercises',
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.flow_id'], ),
    sa.PrimaryKeyConstraint('flow_id', 'exercise_id')
    )
    op.create_table('workouts',
    sa.Column('workout_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.Column('n_sets', sa.Integer(), nullable=False),
    sa.Column('n_reps', sa.Integer(), nullable=False),
    sa.Column('durations', sa.String(), nullable=False),
    sa.Column('skip', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.flow_id'], ),
    sa.PrimaryKeyConstraint('workout_id'),
    sa.UniqueConstraint('lecture_id')
    )
    op.create_table('executions',
    sa.Column('execution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.workout_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executions')
    op.drop_table('workouts')
    op.drop_table('flow_exercises')
    op.drop_table('flows')
    op.drop_table('exercises')
    # ### end Alembic commands ###
