/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/exercises': RouteRecordInfo<
      '/exercises',
      '/exercises',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/flows/': RouteRecordInfo<
      '/flows/',
      '/flows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/flows/[flow_id]': RouteRecordInfo<
      '/flows/[flow_id]',
      '/flows/:flow_id',
      { flow_id: ParamValue<true> },
      { flow_id: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practice/[workout_id]': RouteRecordInfo<
      '/practice/[workout_id]',
      '/practice/:workout_id',
      { workout_id: ParamValue<true> },
      { workout_id: ParamValue<false> },
      | never
    >,
    '/update-password': RouteRecordInfo<
      '/update-password',
      '/update-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
      views:
        | never
    }
    'src/pages/exercises.vue': {
      routes:
        | '/exercises'
      views:
        | never
    }
    'src/pages/flows/index.vue': {
      routes:
        | '/flows/'
      views:
        | never
    }
    'src/pages/flows/[flow_id].vue': {
      routes:
        | '/flows/[flow_id]'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/practice/[workout_id].vue': {
      routes:
        | '/practice/[workout_id]'
      views:
        | never
    }
    'src/pages/update-password.vue': {
      routes:
        | '/update-password'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
