"""Setup scrape database

Revision ID: 1872764b4340
Revises: 
Create Date: 2024-05-02 15:20:13.388707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1872764b4340'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('mod_lecture_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('exercise_id'),
    sa.UniqueConstraint('lecture_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('flows',
    sa.Column('flow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('A', 'B', 'C', 'D', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('flow_id'),
    sa.UniqueConstraint('level', 'name')
    )
    op.create_table('flow_exercises',
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.flow_id'], ),
    sa.PrimaryKeyConstraint('flow_id', 'exercise_id')
    )
    op.create_table('workouts',
    sa.Column('workout_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('n_sets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.flow_id'], ),
    sa.PrimaryKeyConstraint('workout_id'),
    sa.UniqueConstraint('lecture_id')
    )
    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('n_reps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.workout_id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('flow_exercises')
    op.drop_table('flows')
    op.drop_table('exercises')
    # ### end Alembic commands ###
